// Fixed identifiers shared between ContentGuardAgent and ContentGuardDaemon -
// bundle IDs, LaunchAgent/LaunchDaemon labels, log locations. Distinct from
// Config.swift, which holds *tunable* values (intervals, thresholds) - these
// are identity, not behavior, and changing one means updating the matching
// LaunchAgents/LaunchDaemons plist and re-signing/re-pushing PPPC too.

import Foundation

enum ContentGuardIdentifiers {
    /// The real deployed Worker (worker/wrangler.toml's `routes`) -
    /// SafeAppsSyncClient's only network destination, and the only
    /// outbound network call anything on this Mac (agent or daemon)
    /// makes to infrastructure this project itself runs. Real value, not
    /// a placeholder - same "don't guess a real value" treatment
    /// wrangler.toml's own header comment already applies to everything
    /// else in this project.
    static let panelBaseURL = "https://panel.lukep009.download"

    /// Matches profiles/pppc.mobileconfig's __BUNDLE_ID__ once filled in, and
    /// the CFBundleIdentifier baked into the agent's Info.plist.
    static let agentBundleID = "com.contentguard.agent"

    /// The daemon isn't a TCC-gated app (it never touches Screen
    /// Recording/Accessibility directly), so it doesn't need PPPC - but it
    /// does need a stable identifier for its LaunchDaemon label and logging.
    static let daemonBundleID = "com.contentguard.daemon"

    /// Must match LaunchAgents/com.contentguard.agent.plist's Label key.
    static let agentLaunchLabel = "com.contentguard.agent"

    /// Must match LaunchDaemons/com.contentguard.daemon.plist's Label key.
    static let daemonLaunchLabel = "com.contentguard.daemon"
}

enum ContentGuardPaths {
    static let modelDirectory = "/usr/local/share/contentguard"
    static let modelFile = "\(modelDirectory)/nudenet_640m.onnx"

    static let logDirectory = "/usr/local/var/log/contentguard"
    static let agentLogFile = "\(logDirectory)/agent.log"
    static let daemonLogFile = "\(logDirectory)/daemon.log"

    /// Where BlackoutTimer/EscalationManager persist state that needs to
    /// survive a daemon restart (e.g. mid-blackout across a crash/relaunch).
    /// Root-owned, not user-writable - the daemon is the only thing that
    /// should ever touch this.
    static let daemonStateFile = "/usr/local/var/lib/contentguard/state.json"

    /// The dashboard-adjustable safe-app-bundle-ID cache
    /// (SafeAppsSyncClient, daemon-side) - the on-disk counterpart to
    /// worker/src/daemonSync.ts's GET /sync/safe-apps response, same JSON
    /// shape (SafeAppsSyncFile below), no on-disk transformation. Written
    /// ONLY by the daemon (root), after a successful, validated fetch -
    /// world-readable (0644), unlike daemonStateFile above, specifically
    /// so AppScopeManager (agent-side, runs as the logged-in user, not
    /// root) can read it directly with no IPC round-trip. A normal user
    /// process still can't write it, since only root owns this path -
    /// that's the actual security property this file depends on.
    static let safeAppsSyncFile = "/usr/local/var/lib/contentguard/safe-apps.json"

    /// Root-only-readable (0600) shared secret SafeAppsSyncClient sends
    /// as the X-ContentGuard-Daemon-Token header on every
    /// GET /sync/safe-apps request (worker/src/auth.ts's
    /// requireDaemonSyncToken). Provisioned manually after install, same
    /// as this project's other server-side secrets (SANTA_SYNC_TOKEN,
    /// FLEET_API_TOKEN) are manually set up via `wrangler secret put`
    /// rather than committed or auto-generated by the installer - a
    /// secret unique to one deployment has no business in this repo or
    /// in Installer/build-pkg.sh. Missing entirely is a valid, safe
    /// state (SafeAppsSyncClient just has nothing to sync yet, per its
    /// own doc comment) - never treated as "use no token."
    static let daemonSyncTokenFile = "/usr/local/var/lib/contentguard/daemon-sync-token"
}

/// Wire/cache shape for ContentGuardPaths.safeAppsSyncFile - shared
/// between SafeAppsSyncClient (daemon, writes it after validating a real
/// GET /sync/safe-apps response) and AppScopeManager (agent, reads it)
/// so the two sides can't drift out of sync on what this file's JSON
/// looks like. Matches worker/src/daemonSync.ts's response body exactly -
/// deliberately identical, no on-disk transformation, since this is
/// otherwise a pure pass-through cache.
struct SafeAppsSyncFile: Codable {
    let bundle_ids: [String]
}
